[tool.poetry]
name = "yt-nexus"
version = "0.1.0"
description = "A Flask API for accessing YouTube video transcripts, channel information, and related data."
authors = ["Keagan Gilmore <keagangilmore@gmail.com>"]
license = "Proprietary"

[tool.poetry.dependencies]
python = "^3.8"
flask = "^2.0"
flask-cors = "^3.1"
sqlite = "*"
yt-dlp = "*"
scrapetube = "*"
youtubesearchpython = "*"

[tool.poetry.dev-dependencies]
pytest = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
